version: "3.3"
services:
  time-manager-api:
    container_name: time-manager-api
    build: .
    environment:
      - PHX_HOST="0.0.0.0"
    env_file:
      - .env
    ports:
      - ${ELIXIR_PORT}:4000
    command: sh -c "mix ecto.migrate && mix phx.server"
    volumes:
      - .:/app
    depends_on:
      - time-manager-db

  time-manager-db:
    container_name: time-manager-db
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
