version: "3.3"
services:
  elixir-api:
    container_name: elixir-api
    build: .
    environment:
      # - POSTGRES_USER=${POSTGRES_USER}
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=${POSTGRES_DB}
      # - POSTGRES_HOST=${POSTGRES_HOST}
      # - POSTGRES_PORT=5432
      # # - PGHOST=api-db
      - PHX_HOST="0.0.0.0"
    ports:
      - 4000:4000
    command: sh -c "mix ecto.migrate && mix phx.server"
    volumes:
      - .:/app
    depends_on:
      - api-db

  api-db:
    container_name: api-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_dev
    ports:
      -
