name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-push :
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose -f docker-compose.prod.yml build
     
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: musubi42
        password: ôg»¤Æ³ÇÅA!çûp#D9oÑ@Ó§
    - name: Docker Push GH Action
      run: docker compose -f docker-compose.prod.yml push